name: 🚀 yourfirebasesite.com
on:
  push:
    branches:
      - master
    paths:
      - public/**

jobs:
  build:
    name: ⛅ firebase deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: 
        run: |
          npm install -g firebase-tools
          firebase --token $FIREBASE_TOKEN --project ${PROJECT_ID} deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: your-project-id
